name: fakenews-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - beautifulsoup4=4.9.1
  - blas=1.0
  - bs4=4.9.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - icu=58.2
  - idna=2.9
  - intel-openmp=2020.1
  - joblib=0.15.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.5.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - nltk=3.4.5
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pip=20.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyphen=0.9.5
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - readline=8.0
  - requests=2.23.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=47.1.1
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.31.1
  - textstat=0.6.2
  - tk=8.6.8
  - urllib3=1.25.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - fake-useragent==0.1.11
